version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command:
            sudo pip install pytest
      - run:
          command:
            sudo pip install -r requirements.txt
      - run:
          command:
            pytest