version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command:
            sudo pip install pytest
            pytest -m tests
            pytests
